#!/usr/bin/env python3
"""
Generate pixel masks for every node in the MuNG Studio documents.

Policy:
  - Nodes that ALREADY have a mask are kept untouched (those were made with the
    binarize tool over a hand-drawn region and are cleaner around overlaps).
  - Nodes WITHOUT a mask get one generated by binarizing the actual ink of the
    source image inside their bounding box (global Otsu threshold per page).

Result: 100% mask coverage, consistent with MUSCIMA++ (which is 100% masked),
so the data can be shown shape-only in the tool and used for segmentation
experiments. Writes back into documents/<doc>/mung.xml (already backed up).

NOTE on overlap: a pure box-level binarization for a large symbol (slur/beam)
also captures the ink of the symbols it arcs/spans over. Compact symbols are
clean. Existing hand-region masks are preserved precisely to avoid this on the
symbols where it matters most.
"""
import glob, os, sys
import numpy as np
from PIL import Image
from mung.io import read_nodes_from_file, write_nodes_to_file

DOCROOT = "/home/users/yh477/lab/mung-studio-schenker/documents"


def otsu_binary(gray: np.ndarray) -> np.ndarray:
    """Return boolean ink mask (True = ink), foreground = minority class."""
    hist, _ = np.histogram(gray.ravel(), 256, (0, 256))
    total = gray.size
    sum_all = np.dot(np.arange(256), hist)
    wB = 0.0
    sB = 0.0
    best = -1.0
    thr = 127
    for t in range(256):
        wB += hist[t]
        if wB == 0:
            continue
        wF = total - wB
        if wF == 0:
            break
        sB += t * hist[t]
        mB = sB / wB
        mF = (sum_all - sB) / wF
        var = wB * wF * (mB - mF) ** 2
        if var > best:
            best = var
            thr = t
    b = gray <= thr
    if b.mean() > 0.5:          # ink should be the minority
        b = ~b
    return b


def find_image(doc_dir):
    for ext in ("png", "jpg", "jpeg"):
        p = os.path.join(doc_dir, f"image.{ext}")
        if os.path.exists(p):
            return p
    return None


def process(mung_path, doc_name):
    doc_dir = os.path.dirname(mung_path)
    img_path = find_image(doc_dir)
    if img_path is None:
        print(f"  [skip] no image for {doc_name}")
        return None
    gray = np.asarray(Image.open(img_path).convert("L"))
    ink = otsu_binary(gray)
    H, W = ink.shape

    nodes = read_nodes_from_file(mung_path)
    n_kept = n_gen = n_empty = 0
    for n in nodes:
        if n.mask is not None:
            n_kept += 1
            continue
        h, w = int(n.height), int(n.width)
        if h <= 0 or w <= 0:
            continue
        mask = np.zeros((h, w), dtype=np.uint8)
        t0, l0 = max(0, n.top), max(0, n.left)
        b0, r0 = min(H, n.top + h), min(W, n.left + w)
        if b0 > t0 and r0 > l0:
            sub = ink[t0:b0, l0:r0].astype(np.uint8)
            oy, ox = t0 - n.top, l0 - n.left
            mask[oy:oy + sub.shape[0], ox:ox + sub.shape[1]] = sub
        if mask.sum() == 0:        # never leave a degenerate empty mask
            mask[:] = 1
            n_empty += 1
        n.set_mask(mask)
        n_gen += 1

    write_nodes_to_file(nodes, mung_path, document=doc_name)
    return (len(nodes), n_kept, n_gen, n_empty)


def main():
    docs = sorted(glob.glob(os.path.join(DOCROOT, "*", "mung.xml")))
    print(f"{'document':<40}{'nodes':>7}{'kept':>7}{'gen':>7}{'empty':>7}")
    tot = [0, 0, 0, 0]
    for m in docs:
        doc_name = os.path.basename(os.path.dirname(m))
        res = process(m, doc_name)
        if res is None:
            continue
        for i in range(4):
            tot[i] += res[i]
        print(f"{doc_name:<40}{res[0]:>7}{res[1]:>7}{res[2]:>7}{res[3]:>7}")
    print(f"{'TOTAL':<40}{tot[0]:>7}{tot[1]:>7}{tot[2]:>7}{tot[3]:>7}")

    # ---- verification: re-read and confirm 100% coverage + valid round-trip ----
    print("\n=== verification (re-read written files) ===")
    bad = 0
    cov_n = cov_m = 0
    for m in docs:
        ns = read_nodes_from_file(m)
        for n in ns:
            cov_n += 1
            if n.mask is not None:
                cov_m += 1
                a = np.asarray(n.mask)
                if a.shape != (n.height, n.width):
                    bad += 1
    print(f"mask coverage after generation: {cov_m}/{cov_n} = {100*cov_m/max(1,cov_n):.2f}%")
    print(f"nodes with mask-shape != bbox-size (should be 0): {bad}")


if __name__ == "__main__":
    main()
